### PR TITLE
Revert "lpm3, xloader: fix spi2 and i2c0 clock slow issue"

### PR DESCRIPTION
**Pull request by hzhuang1**
This reverts commit 92f365073cd812a8d8ca159b01f52dd6dd06d111.

Since this commit causes kernel hang. Log is in below.

[    0.919490] schedtune: SYSTEM            min_pwr:     0 max_pwr:  6321
[    0.926092] schedtune: using normalization constants mul:
1271299449 sh1: 1 sh2: 12
[    0.933854] schedtune: verify normalization constants...
[    0.939233] schedtune: max_pwr/2^0: 6321 => norm_pwr:  1024
[    0.944884] schedtune: max_pwr/2^1: 3160 => norm_pwr:   511
[    0.950518] schedtune: max_pwr/2^2: 1580 => norm_pwr:   255
[    0.956152] schedtune: max_pwr/2^3:  790 => norm_pwr:   127
[    0.961785] schedtune: max_pwr/2^4:  395 => norm_pwr:    63
[    0.967418] schedtune: max_pwr/2^5:  197 => norm_pwr:    31
[    0.973051] schedtune: configured to support 5 boost groups
[    0.994847] cpuidle: using governor ladder
[    1.019033] cpuidle: using governor menu
[    1.023126] Registered FIQ tty driver
[    1.026934] serial_debugger: uart overlay applied
[    1.032170] vdso: 2 pages (1 code @ ffffff8008cd7000, 1 data @
ffffff8009194000)
[    1.039748] hw-breakpoint: found 6 breakpoint and 4 watchpoint registers.
[    1.047813] DMA: preallocated 256 KiB pool for atomic allocations
[    1.054206] Serial: AMBA PL011 UART driver
[    1.058807] ramoops ramoops: failed to locate DT /reserved-memory resource
[    1.066040] ramoops: probe of ramoops failed with error -22
[    1.094797] hi3660-mbox e896b000.mailbox: Mailbox enabled

### CODE REVIEW

**Comment by vchong** [comment]
@hzhuang1 Are you going to merge this?

**Comment by hzhuang1** [comment]
@docularxu What's your opinion?

**Comment by hzhuang1** [comment]
Drop it since the issue is fixed.

**Comment by vchong** [comment]
Fixed in https://github.com/96boards-hikey/OpenPlatformPkg/pull/61.

**Comment by vchong** [comment]
Also https://github.com/96boards-hikey/OpenPlatformPkg/pull/62.

**Pull request closed without merging**
