### PR TITLE
add picocom as a viable alternative to minicom

### PR DESCRIPTION
**Pull request by ric96**

### CODE REVIEW

**Comment by axel-h** [comment]
seems  good idea to me to mention picocom. It's a nice lightweight tool, I prefer it over minicom.

**Comment by ric96** [comment]
afaik isn't soft flow recommended ?
I might be mistaken

**Comment by axel-h** [comment]
Seem it does not harm to use this in most cases. But it might not be implemented and thus get ignored.

**Comment by docularxu** [comment]
With pull request 16 submitted, close this one.

**Pull request closed without merging**
